"""Attach Amazon ORDER_CHANGE S02 identity to the existing MCF order.

Amazon MCF ORDER_CHANGE carries the Amazon order id plus the existing
sellerFulfillmentOrderItemId generated by BT38 (MCF-...-<item id>). This module
uses that already-persisted identity to attach the S02 id to MCFOrder. It does
not create an order, inventory mutation, provider read, worker, poller, or
marketplace write.
"""
from __future__ import annotations

from datetime import datetime
from typing import Any

from services import governed_webhook_execution as webhook_execution


def _walk(value: Any):
    if isinstance(value, dict):
        for key, item in value.items():
            yield str(key), item
            yield from _walk(item)
    elif isinstance(value, list):
        for item in value:
            yield from _walk(item)


def _extract_identity(payload: dict) -> tuple[set[str], set[str]]:
    """Return exact BT38 seller-fulfilment ids and Amazon S02 ids."""
    seller_ids: set[str] = set()
    amazon_ids: set[str] = set()

    for key, value in _walk(payload or {}):
        if value in (None, ""):
            continue
        normalized = key.replace("_", "").strip().lower()
        text = str(value).strip()

        if normalized == "sellerfulfillmentorderid" and text.upper().startswith("MCF-"):
            seller_ids.add(text)
            continue

        if normalized == "sellerfulfillmentorderitemid" and text.upper().startswith("MCF-"):
            candidate = text.rsplit("-", 1)[0]
            if candidate:
                seller_ids.add(candidate)
            continue

        if normalized == "amazonorderid" and text.upper().startswith("S02-"):
            amazon_ids.add(text)

    return seller_ids, amazon_ids


def bind_mcf_amazon_order_identity(payload: dict) -> dict[str, Any]:
    """Idempotently bind one exact S02 id to one existing MCFOrder."""
    from extensions import db
    from models import MCFOrder, SystemLog

    seller_ids, amazon_ids = _extract_identity(payload or {})
    if not seller_ids or not amazon_ids:
        return {
            "applicable": False,
            "changed": False,
            "reason": "mcf_order_change_identity_incomplete",
        }

    matches = (
        MCFOrder.query
        .filter(MCFOrder.seller_fulfillment_order_id.in_(seller_ids))
        .order_by(MCFOrder.id.desc())
        .all()
    )
    if not matches:
        return {
            "applicable": True,
            "changed": False,
            "reason": "mcf_order_not_found",
            "seller_fulfillment_order_ids": sorted(seller_ids),
            "amazon_order_ids": sorted(amazon_ids),
        }

    mcf = matches[0]
    incoming = sorted(amazon_ids)[0]
    current = str(getattr(mcf, "amazon_order_id", None) or "").strip()

    if current and current != incoming:
        db.session.add(SystemLog(
            log_type="mcf_identity_conflict",
            message=f"MCF order {mcf.id} Amazon order identity conflict",
            details=(
                f"seller_fulfillment_order_id={mcf.seller_fulfillment_order_id};"
                f"current_amazon_order_id={current};incoming_amazon_order_id={incoming}"
            ),
        ))
        db.session.commit()
        return {
            "applicable": True,
            "changed": False,
            "conflict": True,
            "reason": "amazon_order_id_conflict",
            "mcf_order_id": int(mcf.id),
            "amazon_order_id": current,
            "incoming_amazon_order_id": incoming,
        }

    if current == incoming:
        return {
            "applicable": True,
            "changed": False,
            "reason": "amazon_order_id_already_bound",
            "mcf_order_id": int(mcf.id),
            "amazon_order_id": current,
        }

    mcf.amazon_order_id = incoming
    mcf.amazon_status_updated_at = datetime.utcnow()
    db.session.commit()
    return {
        "applicable": True,
        "changed": True,
        "reason": "amazon_order_id_bound",
        "mcf_order_id": int(mcf.id),
        "seller_fulfillment_order_id": str(mcf.seller_fulfillment_order_id),
        "amazon_order_id": incoming,
    }


def _install() -> None:
    if getattr(webhook_execution, "_bt38_mcf_order_identity_patched", False):
        return

    original = webhook_execution.process_marketplace_notification

    def aligned_process_marketplace_notification(
        *,
        marketplace: str,
        payload: dict,
        actor: str = "marketplace_webhook",
        notification_record_id: int | None = None,
    ):
        platform = str(marketplace or (payload or {}).get("marketplace") or "").strip().lower()
        event_type = str(webhook_execution._event_type(payload or {}) or "").strip().upper()
        identity = None

        if platform == "amazon" and event_type == "ORDER_CHANGE":
            try:
                identity = bind_mcf_amazon_order_identity(payload or {})
            except Exception as exc:
                try:
                    from extensions import db
                    db.session.rollback()
                except Exception:
                    pass
                identity = {
                    "applicable": True,
                    "changed": False,
                    "reason": "mcf_order_identity_alignment_failed",
                    "error": str(exc),
                }

        result = original(
            marketplace=marketplace,
            payload=payload,
            actor=actor,
            notification_record_id=notification_record_id,
        )
        if identity is not None and isinstance(result, dict):
            result = dict(result)
            result["mcf_order_identity"] = identity
        return result

    webhook_execution.process_marketplace_notification = aligned_process_marketplace_notification
    webhook_execution._bt38_mcf_order_identity_patched = True


_install()
